signer-config:
  sidecar:
    sidecar_url: "${KMS_SIDECAR_URL}"
rpc-host-ip: 0.0.0.0
rpc-port: ${PORT}
metrics-port: 9184
gas-pool-config:
  redis:
    redis_url: "${REDIS_URL}"
fullnode-url: "${FULLNODE_URL}"
coin-init-config:
  target-init-balance: 100000000  # 0.1 MYSO in MIST
  refresh-interval-sec: 86400     # 24 hours
daily-gas-usage-cap: 15000000000000  # 15000 MYSO in MIST 